name = "splash-multiplayer"
main = "src/index.ts"
compatibility_date = "2024-11-01"

workers_dev = true

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" }
]

[[migrations]]
tag = "v3"
deleted_classes = ["GameRoom"]
new_sqlite_classes = ["Room"]
